### ISSUE TITLE
Removing AWS keys dependency from Manager Node.

### ISSUE THREAD

**Issue by AmalQB** [microservices-today/IaC-manager#17]
Create a new AWS IAM role and bind it with the Manager node.
After this we can run `terraform apply` from the manager node without AWS Keys.

**Comment by kamoljan** [comment]
@AmalQB did you try it?

**Comment by AmalQB** [comment]
@kamoljan yes , it would be similar to how we attach role to instances for s3bucket access.

**Comment by kamoljan** [comment]
@AmalQB 👍

**Comment by alexraju** [comment]
Fixed with https://github.com/microservices-today/IaC-manager/pull/39
