### ISSUE TITLE
generate docs.sh not working

### ISSUE THREAD

**Issue by fr-kshibata** [microservices-today/IaC-manager#54]
```
user@machine IaC-manager (master) $ ./generate-docs.sh
./generate-docs.sh: line 3: terraform-docs: command not found
user@machine IaC-manager (master) $

```

please check

**Comment by alexraju** [comment]
[Terraform-docs](https://github.com/segmentio/terraform-docs) is a pre-requisite for running generate-docs.sh. Could you try after installing Terraform-docs. Will update README accordingly. (We are using `./generate-docs.sh` to generate documentation for terraform code)

**Comment by kamoljan** [comment]
@fr-kshibata thank you for your feedback!
