### ISSUE TITLE
Maybe need to move terraform package to our own registry to speedup installation process?

### ISSUE THREAD

**Issue by kamoljan** [microservices-today/IaC-manager#8]

**Comment by alexraju** [comment]
Considering moving to S3 or CDN. Need to check out the performance improvement for this.

**Comment by alexraju** [comment]
@kamoljan With new Terraform 0.7, the installation file size is considerably reduced to 17 MB.

**Comment by kamoljan** [comment]
@alexraju agree, closing this issue
